### ISSUE TITLE
Create Google Doc's To Track Achievements

### ISSUE THREAD

**Issue by ghost** [Geoed2000/Employ-Pass#7]
*These need to represent the tables included in The Employability Passport and should look extremely professional Do your best to make them as easy to populate and understand as possible*
- [x] Find tables
- [x] Extract into Google Sheets
- [x] Make them look Fabulous
- [x] Create drop down menus & complex spreadsheet controls

**Comment by ghost** [comment]
@ScanonSDW 
Can you help me with some spreadsheet things please!

**Comment by ScanonSDW** [comment]
no
